users:
    bferch: ENC[AES256_GCM,data:TngIf9bi5Ief6U5qLA3HnosxYND+1evdoq6x3kk4Rao3N71HsjGW3Kp3h2ZUahafUtOD14TOCMzl4ew0g/x7MFY6QFjaM7bT3aVEc8j94aqGG+36QvpMnRnlCK7w0asyRLsoslDQxh5fUA==,iv:RAzKHGZLTIa/rpVnyhGG5NA2WpwbjPjqBZ1AIlityVI=,tag:bS2e9B7nudwPqUBBEEQdqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cvaw3hxqwu8p75mrfzv3u6mgcxks8yhkvz47a3l0wm4wtutageyqezgpqw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTXp6QmVNVWxkSytEOG1S
            c1VKck54blRpU3pDaW1zN2JtNEp3TGxBUERnCnVQRjhZYXYrVHpLVFRFN2hHWXE1
            VHVabklPUWxMV1lMalpuMm1sVEhiSGsKLS0tIEpvcmdEOVlvblQ3VUREd0phQ1Vu
            TXBZUFU5NmJHSnRMUnhMRjNCMHZKK1UKoXNoqGawZ/cjb3Hi80hjjoRpi9xjcKig
            e899K0ybVIM3p6PEh3PUfw6pfwu4vsx3NlzNiEUzRnTfg9WghkrpkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T18:58:14Z"
    mac: ENC[AES256_GCM,data:WxdbPdik8T7PAF4JpzacfyOVVxOG9bS8oJcih5aPWonlz9l1IKVDQGySXPdTicOvfutRNMaLMupIRTrFjgLofJi3CbAixObpsOOybAXj01qCejeH0kvrN3AtHC4+pbr/+u/KBAfeIUST2gZIzwI/n/xVWlSaDwXXVU17eMBaWkg=,iv:PHpqaFbDUUgUdurCNcp4m7XFveV9cCdbXdBKT1yyw88=,tag:jhvJOxG8Pd0gEr1fqfdDPA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
